import express from 'express';
import crypto from 'crypto';
import { query } from '../db/pool.js';

const router = express.Router();

// Simple API key middleware
function requireApiKey(req, res, next) {
  const key = req.header('x-api-key') || req.query.api_key;
  const expected = process.env.AI_TOOL_API_KEY;
  if (!expected) return res.status(500).json({ error: 'AI_TOOL_API_KEY not configured' });
  if (!key || key !== expected) return res.status(401).json({ error: 'Unauthorized' });
  next();
}

// Naive in-memory rate limit per key
const buckets = new Map();
function rateLimit(maxPerMinute = 60) {
  return (req, res, next) => {
    const key = req.header('x-api-key') || 'anon';
    const now = Date.now();
    const windowMs = 60 * 1000;
    const bucket = buckets.get(key) || [];
    const recent = bucket.filter((t) => now - t < windowMs);
    if (recent.length >= maxPerMinute) return res.status(429).json({ error: 'Rate limit exceeded' });
    recent.push(now);
    buckets.set(key, recent);
    next();
  };
}

// Discovery manifest for Opal-like tools
router.get('/discovery', requireApiKey, rateLimit(30), (req, res) => {
  res.json({
    schema_version: '1.0',
    name_for_human: 'Petal HR Tools',
    name_for_model: 'petal_hr_tools',
    description_for_human: 'Roster generation, CSV diagnostics, and HR policy explanations.',
    description_for_model: 'Use these tools to generate shift rosters, validate CSV mappings, and explain HR policy thresholds.',
    api: {
      type: 'openapi',
      url: `${req.protocol}://${req.get('host')}/api/ai/openapi.json`,
    },
    auth: { type: 'api_key', name: 'x-api-key' }
  });
});

// OpenAPI (minimal) for discovery
router.get('/openapi.json', requireApiKey, (req, res) => {
  res.json({
    openapi: '3.0.0',
    info: { title: 'Petal HR AI Tools', version: '1.0.0' },
    paths: {
      '/api/ai/roster/generate': { post: { summary: 'Generate roster' } },
      '/api/ai/csv/diagnose': { post: { summary: 'Diagnose CSV mapping' } },
      '/api/ai/policy/explain': { get: { summary: 'Explain policy' } }
    }
  });
});

// Roster generation (heuristics placeholder)
router.post('/roster/generate', requireApiKey, rateLimit(20), express.json(), async (req, res) => {
  const { start_date, end_date, roles_needed, max_hours_per_employee, unavailable_employee_ids = [] } = req.body || {};
  if (!start_date || !end_date || !Array.isArray(roles_needed)) return res.status(400).json({ error: 'Missing fields' });

  // Minimal heuristic: return empty draft and id; real generation can call LLM via serverless function
  const tenantId = null; // Will be set when called from authenticated admin via backend; external tool has no tenant
  const draft = { start_date, end_date, roles_needed, assignments: [], notes: 'Draft generated by heuristic v1' };
  res.json({ draft });
});

// CSV diagnose: validate mapping on sample rows
router.post('/csv/diagnose', requireApiKey, rateLimit(30), express.json(), async (req, res) => {
  const { rows = [], mapping = {} } = req.body || {};
  if (!Array.isArray(rows) || rows.length === 0) return res.status(400).json({ error: 'No rows provided' });
  const required = ['first_name','last_name','email','employee_id','role'];
  const errors = [];
  const warnings = [];
  const mappedFields = Object.values(mapping || {});
  for (const f of required) if (!mappedFields.includes(f)) errors.push(`Missing mapping for required field: ${f}`);
  // Validate emails and duplicates in sample
  const seen = new Set();
  rows.slice(0, 10).forEach((r, idx) => {
    const email = r[mapping.email];
    const empId = r[mapping.employee_id];
    if (!email || !/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)) errors.push(`Row ${idx + 1}: invalid email`);
    if (!empId) errors.push(`Row ${idx + 1}: missing employee_id`);
    const key = `${email}|${empId}`;
    if (seen.has(key)) warnings.push(`Row ${idx + 1}: duplicate in sample`);
    seen.add(key);
  });
  res.json({ ok: errors.length === 0, errors, warnings });
});

// Policy explain
router.get('/policy/explain', requireApiKey, rateLimit(60), async (req, res) => {
  const topic = req.query.topic || 'leave-approval';
  if (topic === 'leave-approval') {
    res.json({
      topic,
      text: 'Leaves over the configured threshold require Manager then HR approvals. Default threshold is 10 days. Standard leaves require only Manager approval.'
    });
  } else if (topic === 'expense-approval') {
    res.json({
      topic,
      text: 'Expenses over the configured amount require Manager then HR approvals. Default threshold is 10,000.'
    });
  } else {
    res.json({ topic, text: 'Policy not found.' });
  }
});

export default router;


